export const sampleProducts = [
  {
    name: 'Polo Sporting Stretch Shirt',
    slug: 'polo-sporting-stretch-shirt',
    category: 'Shirts',
    brand: 'Polo',
    description:
      'Comfortable stretch polo shirt perfect for casual and sporting activities. Made with high-quality materials for durability and comfort.',
    stock: 15,
    images: ['/images/polo-shirt.jpg', '/images/screen.png'],
    price: '59.99',
    rating: '4.5',
    numReviews: 12,
    isFeatured: true,
    banner: '/images/banner-1.jpg',
  },
  {
    name: 'Brooks Brothers Long Sleeved Shirt',
    slug: 'brooks-brothers-long-sleeved-shirt',
    category: 'Shirts',
    brand: 'Brooks Brothers',
    description:
      'Classic long-sleeved dress shirt with traditional styling. Perfect for professional and formal occasions.',
    stock: 8,
    images: ['/images/dress-shirt.jpg', '/images/screen.png'],
    price: '85.90',
    rating: '4.0',
    numReviews: 8,
    isFeatured: false,
    banner: null,
  },
  {
    name: 'Tommy Hilfiger Classic Fit Dress Shirt',
    slug: 'tommy-hilfiger-classic-fit-dress-shirt',
    category: 'Shirts',
    brand: 'Tommy Hilfiger',
    description:
      'Classic fit dress shirt with premium cotton blend. Features traditional collar and button-down design.',
    stock: 0,
    images: ['/images/stretch-shirt.jpg', '/images/screen.png'],
    price: '75.00',
    rating: '4.5',
    numReviews: 15,
    isFeatured: false,
    banner: null,
  },
  {
    name: 'Calvin Klein Slim Fit Stretch Shirt',
    slug: 'calvin-klein-slim-fit-stretch-shirt',
    category: 'Shirts',
    brand: 'Calvin Klein',
    description:
      'Modern slim fit stretch shirt designed for contemporary style. Offers comfort and flexibility with a tailored look.',
    stock: 12,
    images: ['/images/slim-shirt.jpg', '/images/screen.png'],
    price: '39.95',
    rating: '3.5',
    numReviews: 6,
    isFeatured: true,
    banner: '/images/banner-2.jpg',
  },
  {
    name: 'Premium Business Casual Shirt',
    slug: 'premium-business-casual-shirt',
    category: 'Shirts',
    brand: 'Premium',
    description:
      'High-quality business casual shirt perfect for office wear. Features wrinkle-resistant fabric and professional styling.',
    stock: 20,
    images: ['/images/promo.jpg', '/images/screen.png'],
    price: '45.00',
    rating: '4.2',
    numReviews: 18,
    isFeatured: false,
    banner: null,
  },
];
